### ISSUE TITLE
GitHub-Link on SpigotMC page is incorrect

### ISSUE THREAD

**Issue by SehrGuterCode** [Tahu964/Discord-Bot-Announcer#1]
On SpigotMC, https://github.com/Tahu964/DiscordPlugin is set as the source code, but the real link of the repository is https://github.com/Tahu964/Discord-Bot-Announcer.

**Comment by Tahu964** [comment]
Thank you for pointing that out! I accidently posted the wrong link, this should be changed now. I develop the code on the first repository, while I publish the compiled code on the other (this is done so code doesn't get stolen).
